package fix

import (
	"context"
	"strings"
	"testing"

	"github.com/valolink/hestiascripts/internal/check"
	"github.com/valolink/hestiascripts/internal/sys"
)

func robotsFake(plugins string) *sys.Fake {
	wp := "runuser -u shop -- env HOME=/home/shop wp --path=/home/shop/web/shop.fi/public_html "
	return &sys.Fake{Files: map[string]string{
		"/usr/local/hestia/data/users/shop/user.conf":      "NAME='shop'\n",
		"/usr/local/hestia/data/users/shop/web.conf":       "DOMAIN='shop.fi' IP='1.2.3.4' SSL='yes'\n",
		"/home/shop/web/shop.fi/public_html/wp-config.php": "<?php\n",
	}, Cmds: map[string]sys.FakeCmd{
		wp + "plugin list --status=active --field=name --skip-plugins --skip-themes": {Out: plugins},
		wp + "option get home --skip-plugins --skip-themes":                          {Out: "https://shop.fi\n"},
	}, HTTP: map[string]sys.FakeHTTP{"local https://shop.fi/wp-sitemap.xml": {Status: 200}}}
}

// riverfinland.fi 2026-09-30: Rank Math, no shop, no file → nothing to write.
func TestRobotsPlanRefusesWhenNothingIsNeeded(t *testing.T) {
	f := robotsFake("seo-by-rank-math\n")
	fx, _ := ByID("robots")
	if _, err := fx.Plan(context.Background(), &check.Env{Sys: f}, "shop.fi"); err == nil || !strings.Contains(err.Error(), "nothing to change") {
		t.Errorf("want refusal, got %v", err)
	}
}

func TestRobotsPlanPlaceholder(t *testing.T) {
	f := robotsFake("akismet\n")
	f.Files["/home/shop/web/shop.fi/public_html/robots.txt"] = "# hestiacp autogenerated robots.txt\nUser-agent: *\nCrawl-delay: 10\n"
	fx, _ := ByID("robots")
	steps, err := fx.Plan(context.Background(), &check.Env{Sys: f}, "shop.fi")
	if err != nil || len(steps) != 2 || !strings.Contains(steps[0].Why, "Sitemap: https://shop.fi/wp-sitemap.xml") || steps[0].Argv[1] != "robots" {
		t.Fatalf("plan: %v %+v", err, steps)
	}
}
