package op

// Firewall hardening (docs/security-hardening.md §2, §4 and the IPv6 gap):
// settings in /etc/hs/firewall.conf, rules generated by `hs firewall apply`
// into /etc/hs/firewall.sh (see internal/fwgen), SSH/panel limits written as
// Hestia's own firewall rules.

import (
	"context"
	"fmt"
	"net"
	"os"
	"regexp"
	"strings"

	"github.com/valolink/hestiascripts/internal/check"
	"github.com/valolink/hestiascripts/internal/conf"
	"github.com/valolink/hestiascripts/internal/fwgen"
)

const breakGlass = "Break-glass if locked out: the provider's web console (Hetzner Cloud Console / Robot KVM) gives a root login without SSH; there, `v-change-firewall-rule` the rule back to 0.0.0.0/0 or `v-stop-firewall`."

func fwConf(env *check.Env) fwgen.Config {
	return fwgen.ParseConfig(readFile(env, fwgen.ConfPath))
}

// fwSet: create /etc/hs/firewall.conf if needed, set keys (hs conf set).
func fwSet(why string, kv ...string) []Step {
	return []Step{
		{Why: "hs firewall settings", Argv: []string{"sh", "-c", "install -d -m 700 /etc/hs && [ -e " + fwgen.ConfPath + " ] || install -m 600 /dev/null " + fwgen.ConfPath}},
		confSet(why, fwgen.ConfPath, conf.Opts{Style: conf.Shell}, kv...),
	}
}

func fwApply() Step {
	return Step{Why: "generate /etc/hs/firewall.sh, hook it into Hestia's custom.sh and the boot unit, apply it", Argv: []string{self(), "firewall", "apply"}}
}

// sshClient is the address this session came from (SSH_CONNECTION).
func sshClient() net.IP {
	f := strings.Fields(os.Getenv("SSH_CONNECTION"))
	if len(f) == 0 {
		return nil
	}
	return net.ParseIP(f[0])
}

func parseCIDRs(s string) ([]*net.IPNet, error) {
	var out []*net.IPNet
	for _, f := range strings.Fields(strings.ReplaceAll(s, ",", " ")) {
		if !strings.Contains(f, "/") {
			if strings.Contains(f, ":") {
				f += "/128"
			} else {
				f += "/32"
			}
		}
		_, n, err := net.ParseCIDR(f)
		if err != nil {
			return nil, fmt.Errorf("%q is not an address or range", f)
		}
		out = append(out, n)
	}
	return out, nil
}

func covers(nets []*net.IPNet, ip net.IP) bool {
	for _, n := range nets {
		if n.Contains(ip) {
			return true
		}
	}
	return false
}

func hasTailscale(env *check.Env) bool { return exists(env, "/sys/class/net/tailscale0") }

var portsRe = regexp.MustCompile(`^[0-9]+([ ,][0-9]+)*$`)

func init() {
	register(Op{
		ID: "firewall-ipv6", Title: "Close the IPv6 gap in the firewall", Section: "security", Risk: Change,
		Resolves: "firewall.ipv6",
		Note:     "Hestia's firewall is IPv4-only: over IPv6 every listening service (panel, SSH, Netdata, streamer) is open to everyone. This makes IPv6 follow Hestia's rules: what Hestia opens to all stays open, what it limits to addresses is closed on IPv6 (unless an admin IPv6 range is given).",
		How:      "Sets IPV6_INPUT='mirror' (and ADMIN_V6) in /etc/hs/firewall.conf; `hs firewall apply` generates /etc/hs/firewall.sh — an HS_IN6 chain first in ip6tables INPUT: loopback, established, ICMPv6 (neighbour discovery needs it), DHCPv6, the TCP/UDP ports Hestia's rules.conf opens to 0.0.0.0/0, the admin ranges, then DROP — adds one line to Hestia's custom.sh so every v-update-firewall re-applies it, and enables hs-firewall.service to apply it at boot (Hestia restores only IPv4 then). Sites stay reachable over IPv6 on the ports they already use.",
		Undo:     "Set IPV6_INPUT='off' (hs op firewall-ipv6 mode=off) — the chain is removed.",
		Fields: []Field{
			{Key: "mode", Label: "IPv6 inbound", Kind: Choice,
				Current: func(_ context.Context, env *check.Env, _ Target) string { return fwConf(env).IPv6Input },
				Choices: func(context.Context, *check.Env, Target) [][2]string {
					return [][2]string{{"mirror", "follow Hestia's public rules, drop the rest"}, {"off", "leave IPv6 unfiltered"}}
				}},
			{Key: "admin-v6", Label: "Admin IPv6 ranges", Kind: Text, Optional: true,
				Help: "Space-separated. May reach the ports Hestia limits (SSH, panel) over IPv6. Tailscale's IPv6 range is fd7a:115c:a1e0::/48.",
				Default: func(_ context.Context, env *check.Env, _ Target) string {
					return strings.Join(fwConf(env).AdminV6, " ")
				}},
		},
		Recheck: []string{"firewall.ipv6"},
		Plan: func(_ context.Context, env *check.Env, _ Target, v Values) ([]Step, error) {
			nets, err := parseCIDRs(v["admin-v6"])
			if err != nil {
				return nil, err
			}
			if ip := sshClient(); v["mode"] == "mirror" && ip != nil && ip.To4() == nil {
				pub := fwgen.PublicPorts(fwgen.ParseRules(readFile(env, fwgen.RulesConf)))["tcp"]
				open22 := false
				for _, p := range pub {
					open22 = open22 || p == "22"
				}
				if !open22 && !covers(nets, ip) {
					return nil, fmt.Errorf("refused: this session comes in over IPv6 from %s, SSH is not public in Hestia's rules, and no admin IPv6 range covers it — it would be cut off", ip)
				}
			}
			steps := fwSet("IPv6 inbound "+v["mode"], "IPV6_INPUT", v["mode"], "ADMIN_V6", v["admin-v6"])
			return append(steps, fwApply()), nil
		},
	})

	register(Op{
		ID: "panel-restrict", Title: "SSH and panel only from admin networks", Section: "security", Risk: Destructive,
		Resolves: "panel.exposure",
		Note:     "Limits SSH (22) and the Hestia panel (8083) to the listed networks — the web-terminal compromise needed the panel to be reachable from anywhere. Refused unless this session's own address is covered. " + breakGlass,
		How:      "Hestia's own firewall rules: the rule that opens each port to 0.0.0.0/0 is changed to the first range (`v-change-firewall-rule`), one more rule is added per further range (`v-add-firewall-rule`), and Hestia reloads the firewall. Open sessions survive (established connections are accepted first). With the IPv6 firewall on, these ports are then closed over IPv6 except for the admin IPv6 ranges. EngineLink is unaffected: it uses the streamer (8091), which has its own rule.",
		Undo:     "v-change-firewall-rule RULE ACCEPT 0.0.0.0/0 PORT TCP COMMENT for the changed rule(s) and v-delete-firewall-rule for the added ones (all listed in the plan).",
		Fields: []Field{
			{Key: "sources", Label: "Allowed from", Kind: Text,
				Help: "Space-separated IPv4 addresses/ranges: the office, the admin's fixed IP, 100.64.0.0/10 for Tailscale (only once every admin machine is on it), the EngineLink host if it SSHes in.",
				Current: func(context.Context, *check.Env, Target) string {
					if ip := sshClient(); ip != nil {
						return "this session comes from " + ip.String()
					}
					return "not an SSH session"
				},
				Default: func(_ context.Context, env *check.Env, _ Target) string {
					if hasTailscale(env) {
						return "100.64.0.0/10"
					}
					return ""
				}},
			{Key: "ports", Label: "Ports", Kind: Choice, Choices: func(context.Context, *check.Env, Target) [][2]string {
				return [][2]string{{"22 8083", "SSH and panel"}, {"8083", "panel only"}, {"22", "SSH only"}}
			}},
		},
		Recheck: []string{"panel.exposure", "firewall.ipv6"},
		Plan: func(_ context.Context, env *check.Env, _ Target, v Values) ([]Step, error) {
			nets, err := parseCIDRs(v["sources"])
			if err != nil {
				return nil, err
			}
			if len(nets) == 0 {
				return nil, fmt.Errorf("list at least one allowed address or range")
			}
			for _, n := range nets {
				if n.IP.To4() == nil {
					return nil, fmt.Errorf("%s: Hestia's firewall takes IPv4 only — IPv6 admin ranges go in Close the IPv6 gap", n)
				}
				if ones, _ := n.Mask.Size(); ones == 0 {
					return nil, fmt.Errorf("0.0.0.0/0 is everyone — that is what this removes")
				}
			}
			if ip := sshClient(); ip != nil && strings.Contains(" "+v["ports"]+" ", " 22 ") && !covers(nets, ip) {
				return nil, fmt.Errorf("refused: this session comes from %s, which none of the ranges covers — it would lock you out", ip)
			}
			rules := fwgen.ParseRules(readFile(env, fwgen.RulesConf))
			var steps []Step
			for _, port := range strings.Fields(v["ports"]) {
				var pub *fwgen.Rule
				for i, r := range rules {
					if r.Public() && r.Port == port {
						pub = &rules[i]
					}
				}
				if pub == nil {
					continue // already limited
				}
				comment := pub.Comment
				steps = append(steps, Step{Why: fmt.Sprintf("port %s: rule %s (%s) from 0.0.0.0/0 to %s", port, pub.ID, comment, nets[0]),
					Argv: []string{bin + "v-change-firewall-rule", pub.ID, "ACCEPT", nets[0].String(), port, "TCP", comment}})
				for _, n := range nets[1:] {
					steps = append(steps, Step{Why: fmt.Sprintf("port %s: also from %s", port, n),
						Argv: []string{bin + "v-add-firewall-rule", "ACCEPT", n.String(), port, "TCP", comment + "_admin"}})
				}
			}
			if len(steps) == 0 {
				return nil, nil
			}
			steps = append(steps, Step{Why: "Hestia's rules now", Argv: []string{bin + "v-list-firewall"}})
			if fwConf(env).IPv6Input == "mirror" {
				steps = append(steps, fwApply())
			}
			return steps, nil
		},
	})

	register(Op{
		ID: "egress", Title: "Outbound traffic filter", Section: "security", Risk: Change,
		Resolves: "egress",
		Note:     "Known command-and-control hosts are always dropped. The filter allows DNS, NTP, HTTP(S), mail submission (465/587), the Storage Box (23) and SSH/git (22); everything else is logged (log) or rejected (drop). Run log for a week, allow what is legitimate, then drop.",
		How:      "Sets EGRESS (and EGRESS_EXTRA_PORTS) in /etc/hs/firewall.conf; `hs firewall apply` rebuilds the HS_OUT chain first in OUTPUT for IPv4 and IPv6: the block list from templates/ioc/block-hosts, then loopback and established traffic, ICMP, the allowed ports, a rate-limited LOG with prefix 'hs-egress:' and the sending uid, and in drop mode REJECT (an immediate error for the program, not a hang). The Outbound traffic check summarises the log.",
		Undo:     "hs op egress mode=off (the block list stays).",
		Fields: []Field{
			{Key: "mode", Label: "Filter", Kind: Choice,
				Current: func(_ context.Context, env *check.Env, _ Target) string { return fwConf(env).Egress },
				Choices: func(context.Context, *check.Env, Target) [][2]string {
					return [][2]string{{"log", "log what would be rejected"}, {"drop", "reject everything not allowed"}, {"off", "block list only"}}
				}},
			{Key: "extra", Label: "Also allow TCP ports", Kind: Text, Optional: true, Pattern: portsRe,
				Help: "Space-separated, e.g. 25 when a box delivers mail itself, 3306 for a remote database.",
				Default: func(_ context.Context, env *check.Env, _ Target) string {
					return strings.Join(fwConf(env).EgressExtra, " ")
				}},
		},
		Recheck: []string{"egress"},
		Plan: func(ctx context.Context, env *check.Env, _ Target, v Values) ([]Step, error) {
			steps := fwSet("outbound "+v["mode"], "EGRESS", v["mode"], "EGRESS_EXTRA_PORTS", v["extra"])
			if v["mode"] == "drop" && fwConf(env).Egress != "log" {
				steps[1].Why += "\nNOTE: going to drop without a week of log mode — whatever the allowlist misses breaks at once"
			}
			if v["mode"] == "drop" {
				out, _ := env.Sys.Run(ctx, "journalctl", "-k", "--since=-7d", "--no-pager", "-o", "cat", "--grep", "hs-egress:")
				if n := len(nonEmptyLines(out)); n > 0 {
					steps[1].Why += fmt.Sprintf("\n%d connection(s) logged in 7 days would now be rejected — see the Outbound traffic check", n)
				}
			}
			return append(steps, fwApply()), nil
		},
	})
}
