package op

// Web server: run.sh's Nginx Templates menu (12), and rebuilding the domains
// that use them — a template on disk changes nothing until then.

import (
	"context"
	"fmt"
	"strings"

	"github.com/valolink/hestiascripts/internal/check"
	"github.com/valolink/hestiascripts/internal/hestia"
)

func onHsTemplates(env *check.Env) []hestia.Domain {
	var out []hestia.Domain
	for _, d := range hestia.WebDomains(env.Sys) {
		if strings.HasPrefix(d.Proxy, "wp-") || strings.HasPrefix(d.Tpl, "wp-") {
			out = append(out, d)
		}
	}
	return out
}

func init() {
	register(Op{
		ID: "web-templates", Title: "Install / update web templates", Section: "web", Risk: Change,
		Resolves: "web.templates",
		Note:     "wp-secure (Hestia's default + security rules), wp-rocket, wp-rocket-cartbypass (generated from wp-rocket) as proxy templates, and wp-secure for Apache. Sites keep their current config until rebuilt.",
		How:      "First the cache-headers drop-in (setup/install-cache-headers.sh: nginx -t before it commits, reverts itself on failure) — the templates use the $vl_asset_expires it declares, so `hs templates install` refuses to write them without it. Then: wp-secure = Hestia's default.{tpl,stpl} with the snippet before the first `location / {` (the SSL one rooted at %sdocroot%); wp-rocket copied from the repo; wp-rocket-cartbypass generated by one substitution on wp-rocket's cookie-bypass line and checked three ways; Apache wp-secure inside <Directory %docroot%> / <Directory %sdocroot%> in the directory Hestia reads for this box's backend (apache2/php-fpm here — run.sh wrote apache2/, which php-fpm boxes never read, and its HTTPS copy never got the rules). A template that fails verification is not written. Previous files are kept under /var/lib/hs/backups. Ends with the domains that need a rebuild.",
		Undo:     "Copy the kept templates back (paths printed), then rebuild the domains on them.",
		Recheck:  []string{"web.templates", "web.cache-headers", "web.nginx", "web.template-usage"},
		Plan: func(_ context.Context, env *check.Env, _ Target, _ Values) ([]Step, error) {
			ch, err := repoFile(env, "setup/install-cache-headers.sh")
			if err != nil {
				return nil, err
			}
			return []Step{
				{Why: "the cache-headers drop-in first: the templates reference its $vl_asset_expires", Argv: []string{"bash", ch}},
				{Why: "write and verify the templates", Argv: []string{self(), "templates", "install"}},
			}, nil
		},
	})
	register(Op{
		ID: "web-rebuild", Title: "Rebuild domains on hs templates", Section: "web", Risk: Change,
		Note: "Regenerates each domain's nginx/Apache config from its (updated) template. nginx must accept the result before anything reloads.",
		How:  "`v-rebuild-web-domain USER DOMAIN no` per domain (no restart yet), then `nginx -t` — if it fails nothing is reloaded and the error shows which file — then `v-restart-proxy` and `v-restart-web` reload nginx and Apache once.",
		Undo: "Put the previous template back (web-templates keeps it) and rebuild again.",
		Fields: []Field{{Key: "domain", Label: "Domains", Kind: Choice,
			Choices: func(_ context.Context, env *check.Env, _ Target) [][2]string {
				ds := onHsTemplates(env)
				if len(ds) == 0 {
					return nil
				}
				out := [][2]string{{"all", fmt.Sprintf("all %d on wp-* templates", len(ds))}}
				for _, d := range ds {
					out = append(out, [2]string{d.Name, "proxy " + d.Proxy + ", web " + d.Tpl})
				}
				return out
			}}},
		Recheck: []string{"web.nginx", "web.template-usage", "site.http"},
		Plan: func(_ context.Context, env *check.Env, _ Target, v Values) ([]Step, error) {
			var steps []Step
			for _, d := range onHsTemplates(env) {
				if v["domain"] == "all" || v["domain"] == d.Name {
					steps = append(steps, Step{Why: d.Name, Argv: []string{bin + "v-rebuild-web-domain", d.User, d.Name, "no"}})
				}
			}
			if len(steps) == 0 {
				return nil, fmt.Errorf("no domain on an hs template")
			}
			return append(steps,
				Step{Why: "nginx accepts every generated config", Argv: []string{"nginx", "-t"}},
				Step{Why: "reload", Argv: []string{bin + "v-restart-proxy"}},
				Step{Argv: []string{bin + "v-restart-web"}},
			), nil
		},
	})
}
