package main

import (
	"bufio"
	"crypto/subtle"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"time"
)

const (
	ListenPort = ":8091"
	AllowedDir = "/usr/local/hestia/bin/"
	// Box-local Netdata (setup/netdata.sh). The alarms passthrough dials this
	// so EngineLink never needs a route to :19999 — it only ever talks to us.
	NetdataAlarmsURL = "http://127.0.0.1:19999/api/v1/alarms"
)

// checkToken enforces the shared secret (constant-time) when configured.
// Returns false and writes the 403 when the token is set but doesn't match.
func checkToken(w http.ResponseWriter, r *http.Request) bool {
	if expectedToken == "" {
		return true
	}
	got := r.Header.Get("X-Streamer-Token")
	if subtle.ConstantTimeCompare([]byte(got), []byte(expectedToken)) != 1 {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return false
	}
	return true
}

// Strict regex: The script name must start with "v-" and contain only letters, numbers, and hyphens.
var safeScriptRegex = regexp.MustCompile(`^v-[a-zA-Z0-9-]+$`)

// Shared secret, second factor on top of the firewall IP allowlist.
// Set via the systemd unit's EnvironmentFile (/etc/hestia-streamer.env,
// generated by install-scripts.sh). Empty = auth disabled (pre-token
// installs keep working).
var expectedToken = os.Getenv("HESTIA_STREAMER_TOKEN")

// alarmsHandler proxies the box-local Netdata raised-alarms API back to
// EngineLink. Plain JSON request/response (not SSE) — EngineLink's
// poll-server-alarms cron reconciles the result into ServerAlarm rows and
// notifies on newly-raised CRITICAL alarms. Same token gate as /execute; the
// firewall already restricts :8091 to the Nuxt host.
func alarmsHandler(w http.ResponseWriter, r *http.Request) {
	if !checkToken(w, r) {
		return
	}

	client := http.Client{Timeout: 8 * time.Second}
	resp, err := client.Get(NetdataAlarmsURL)
	if err != nil {
		http.Error(w, fmt.Sprintf("Netdata unreachable: %v", err), http.StatusBadGateway)
		return
	}
	defer resp.Body.Close()

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(resp.StatusCode)
	io.Copy(w, resp.Body)
}

func executeHandler(w http.ResponseWriter, r *http.Request) {
	// 0. Shared-secret check (constant-time compare).
	if !checkToken(w, r) {
		return
	}

	// 1. Setup headers for Server-Sent Events (SSE)
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no") // Prevents Nginx proxy buffering

	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "Streaming unsupported", http.StatusInternalServerError)
		return
	}

	// 2. Parse query parameters
	q := r.URL.Query()
	scriptName := q.Get("script")

	// 3. Security Validation
	// If the script name isn't exactly like "v-clone-wp", reject it immediately.
	if !safeScriptRegex.MatchString(scriptName) {
		fmt.Fprintf(w, "data: ERROR: Invalid or unauthorized script name.\n\n")
		return
	}

	// Construct absolute path securely (prevents directory traversal attacks like "../../bin/bash")
	scriptPath := filepath.Join(AllowedDir, scriptName)

	// 4. Extract dynamic arguments
	// Go automatically groups multiple query parameters with the same name into a string slice []string.
	// E.g., ?arg=--src-user&arg=admin becomes ["--src-user", "admin"]
	args := q["arg"]

	// 5. Execute process safely
	// exec.Command takes the binary path and a variadic list of arguments.
	// It does NOT invoke a shell, rendering standard injection attacks completely useless.
	cmd := exec.Command(scriptPath, args...)
	cmd.Stderr = cmd.Stdout // Merge stderr into stdout so we stream errors too

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		fmt.Fprintf(w, "data: ERROR: Failed to create stdout pipe: %v\n\n", err)
		return
	}

	if err := cmd.Start(); err != nil {
		fmt.Fprintf(w, "data: ERROR: Failed to start script: %v\n\n", err)
		return
	}

	// 6. Stream output line-by-line in real-time
	scanner := bufio.NewScanner(stdout)
	for scanner.Scan() {
		fmt.Fprintf(w, "data: %s\n\n", scanner.Text())
		flusher.Flush()
	}

	// 7. Report the script's exit code as a named SSE event so the caller
	// can distinguish success from failure (EngineLink logs maintenance
	// events / stores captured keys only on exit 0).
	exitCode := 0
	if err := cmd.Wait(); err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
		} else {
			exitCode = -1
		}
	}
	fmt.Fprintf(w, "event: exit\ndata: %d\n\n", exitCode)
	flusher.Flush()
}

func main() {
	http.HandleFunc("/execute", executeHandler)
	http.HandleFunc("/netdata/alarms", alarmsHandler)

	fmt.Printf("🚀 Universal Go Streamer listening on %s...\n", ListenPort)
	if err := http.ListenAndServe(ListenPort, nil); err != nil {
		fmt.Printf("❌ Server failed: %v\n", err)
	}
}
