package main

import (
	"bufio"
	"crypto/subtle"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"
)

const (
	ListenPort = ":8091"
	AllowedDir = "/usr/local/hestia/bin/"
	// Box-local Netdata (setup/netdata.sh). The passthroughs dial this so
	// EngineLink never needs a route to :19999 — it only ever talks to us,
	// which means :19999 can be firewalled off from everything but localhost.
	NetdataBase      = "http://127.0.0.1:19999"
	NetdataAlarmsURL = NetdataBase + "/api/v1/alarms"
)

// Netdata param validators — we build the upstream query ourselves rather than
// forward a raw path, so a caller can never reach arbitrary Netdata endpoints.
var (
	// Slashes are allowed for disk-space chart ids (e.g. "disk_space./home");
	// a "not-contains-.." guard in dataHandler keeps this from being a
	// traversal vector (it's only ever a query-param value anyway).
	safeChartRegex = regexp.MustCompile(`^[a-zA-Z0-9_./]+$`)
	safeDimsRegex  = regexp.MustCompile(`^[a-zA-Z0-9_.,| -]+$`)
	safeGroups     = map[string]bool{"average": true, "max": true, "min": true, "sum": true}
)

// checkToken enforces the shared secret (constant-time) when configured.
// Returns false and writes the 403 when the token is set but doesn't match.
func checkToken(w http.ResponseWriter, r *http.Request) bool {
	if expectedToken == "" {
		return true
	}
	got := r.Header.Get("X-Streamer-Token")
	if subtle.ConstantTimeCompare([]byte(got), []byte(expectedToken)) != 1 {
		http.Error(w, "Forbidden", http.StatusForbidden)
		return false
	}
	return true
}

// Strict regex: The script name must start with "v-" and contain only letters, numbers, and hyphens.
var safeScriptRegex = regexp.MustCompile(`^v-[a-zA-Z0-9-]+$`)

// Dump archives are bare basenames like user_domain_2026-07-05_12-00-00.zip —
// no slashes, must end in .zip. Combined with filepath.Join under the backup
// dir this is the whole reachable surface of downloadHandler.
var safeDumpRegex = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*\.zip$`)

// Shared secret, second factor on top of the firewall IP allowlist.
// Set via the systemd unit's EnvironmentFile (/etc/hestia-streamer.env,
// generated by install-scripts.sh). Empty = auth disabled (pre-token
// installs keep working).
var expectedToken = os.Getenv("HESTIA_STREAMER_TOKEN")

// alarmsHandler proxies the box-local Netdata raised-alarms API back to
// EngineLink. Plain JSON request/response (not SSE) — EngineLink's
// poll-server-alarms cron reconciles the result into ServerAlarm rows and
// notifies on newly-raised CRITICAL alarms. Same token gate as /execute; the
// firewall already restricts :8091 to the Nuxt host.
func alarmsHandler(w http.ResponseWriter, r *http.Request) {
	if !checkToken(w, r) {
		return
	}

	client := http.Client{Timeout: 8 * time.Second}
	resp, err := client.Get(NetdataAlarmsURL)
	if err != nil {
		http.Error(w, fmt.Sprintf("Netdata unreachable: %v", err), http.StatusBadGateway)
		return
	}
	defer resp.Body.Close()

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(resp.StatusCode)
	io.Copy(w, resp.Body)
}

// dataHandler proxies Netdata's read-only time-series API (/api/v1/data) so
// EngineLink can render native charts without exposing :19999 to the browser.
// The upstream query is rebuilt from validated params — never a forwarded raw
// path — so this can only ever hit /api/v1/data with safe values.
func dataHandler(w http.ResponseWriter, r *http.Request) {
	if !checkToken(w, r) {
		return
	}

	q := r.URL.Query()
	chart := q.Get("chart")
	if !safeChartRegex.MatchString(chart) || strings.Contains(chart, "..") {
		http.Error(w, "Invalid chart", http.StatusBadRequest)
		return
	}

	out := url.Values{}
	out.Set("chart", chart)
	out.Set("format", "json")

	// after: negative window in seconds (e.g. -600 = last 10 min). Default -600.
	after := -600
	if v := q.Get("after"); v != "" {
		n, err := strconv.Atoi(v)
		if err != nil || n >= 0 || n < -31_536_000 {
			http.Error(w, "Invalid after", http.StatusBadRequest)
			return
		}
		after = n
	}
	out.Set("after", strconv.Itoa(after))

	// points: capped so a caller can't ask Netdata for an unbounded series.
	if v := q.Get("points"); v != "" {
		n, err := strconv.Atoi(v)
		if err != nil || n < 1 || n > 2000 {
			http.Error(w, "Invalid points", http.StatusBadRequest)
			return
		}
		out.Set("points", strconv.Itoa(n))
	}

	if v := q.Get("group"); v != "" {
		if !safeGroups[v] {
			http.Error(w, "Invalid group", http.StatusBadRequest)
			return
		}
		out.Set("group", v)
	}

	if v := q.Get("dimensions"); v != "" {
		if !safeDimsRegex.MatchString(v) {
			http.Error(w, "Invalid dimensions", http.StatusBadRequest)
			return
		}
		out.Set("dimensions", v)
	}

	client := http.Client{Timeout: 8 * time.Second}
	resp, err := client.Get(NetdataBase + "/api/v1/data?" + out.Encode())
	if err != nil {
		http.Error(w, fmt.Sprintf("Netdata unreachable: %v", err), http.StatusBadGateway)
		return
	}
	defer resp.Body.Close()

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(resp.StatusCode)
	io.Copy(w, resp.Body)
}

// hestiaBackupDir resolves Hestia's $BACKUP (where v-dump-site writes its
// zip) from hestia.conf, defaulting to /backup. Read per request — it's one
// small file and the value can change with a Hestia reconfigure.
func hestiaBackupDir() string {
	data, err := os.ReadFile("/usr/local/hestia/conf/hestia.conf")
	if err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			if strings.HasPrefix(line, "BACKUP=") {
				v := strings.Trim(strings.TrimPrefix(line, "BACKUP="), `'" `)
				if v != "" {
					return v
				}
			}
		}
	}
	return "/backup"
}

// downloadHandler hands a finished v-dump-site archive back to EngineLink.
// Hestia's own panel serves these via nginx X-Accel-Redirect; we don't sit
// behind Hestia's nginx, so the streamer serves the bytes itself. The file
// is deleted after the response ends — the zip is a one-shot handoff, not a
// stored backup (v-dump-site's own `at now + 1 hour` cleanup is only a
// backstop, and `at` isn't installed everywhere).
func downloadHandler(w http.ResponseWriter, r *http.Request) {
	if !checkToken(w, r) {
		return
	}

	name := r.URL.Query().Get("file")
	if !safeDumpRegex.MatchString(name) || strings.Contains(name, "..") {
		http.Error(w, "Invalid file", http.StatusBadRequest)
		return
	}

	path := filepath.Join(hestiaBackupDir(), name)
	f, err := os.Open(path)
	if err != nil {
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil || !info.Mode().IsRegular() {
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	w.Header().Set("Content-Type", "application/zip")
	w.Header().Set("Content-Length", strconv.FormatInt(info.Size(), 10))
	w.Header().Set("Content-Disposition", "attachment; filename="+name)
	io.Copy(w, f)

	// One-shot: remove regardless of whether the client finished reading —
	// an aborted download just means re-running the dump, which beats
	// leaking multi-GB zips on /backup.
	os.Remove(path)
}

func executeHandler(w http.ResponseWriter, r *http.Request) {
	// 0. Shared-secret check (constant-time compare).
	if !checkToken(w, r) {
		return
	}

	// 1. Setup headers for Server-Sent Events (SSE)
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no") // Prevents Nginx proxy buffering

	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "Streaming unsupported", http.StatusInternalServerError)
		return
	}

	// 2. Parse query parameters
	q := r.URL.Query()
	scriptName := q.Get("script")

	// 3. Security Validation
	// If the script name isn't exactly like "v-clone-wp", reject it immediately.
	if !safeScriptRegex.MatchString(scriptName) {
		fmt.Fprintf(w, "data: ERROR: Invalid or unauthorized script name.\n\n")
		return
	}

	// Construct absolute path securely (prevents directory traversal attacks like "../../bin/bash")
	scriptPath := filepath.Join(AllowedDir, scriptName)

	// 4. Extract dynamic arguments
	// Go automatically groups multiple query parameters with the same name into a string slice []string.
	// E.g., ?arg=--src-user&arg=admin becomes ["--src-user", "admin"]
	args := q["arg"]

	// 5. Execute process safely
	// exec.Command takes the binary path and a variadic list of arguments.
	// It does NOT invoke a shell, rendering standard injection attacks completely useless.
	cmd := exec.Command(scriptPath, args...)
	cmd.Stderr = cmd.Stdout // Merge stderr into stdout so we stream errors too

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		fmt.Fprintf(w, "data: ERROR: Failed to create stdout pipe: %v\n\n", err)
		return
	}

	if err := cmd.Start(); err != nil {
		fmt.Fprintf(w, "data: ERROR: Failed to start script: %v\n\n", err)
		return
	}

	// 6. Stream output line-by-line in real-time
	scanner := bufio.NewScanner(stdout)
	for scanner.Scan() {
		fmt.Fprintf(w, "data: %s\n\n", scanner.Text())
		flusher.Flush()
	}

	// 7. Report the script's exit code as a named SSE event so the caller
	// can distinguish success from failure (EngineLink logs maintenance
	// events / stores captured keys only on exit 0).
	exitCode := 0
	if err := cmd.Wait(); err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			exitCode = exitErr.ExitCode()
		} else {
			exitCode = -1
		}
	}
	fmt.Fprintf(w, "event: exit\ndata: %d\n\n", exitCode)
	flusher.Flush()
}

func main() {
	http.HandleFunc("/execute", executeHandler)
	http.HandleFunc("/download", downloadHandler)
	http.HandleFunc("/netdata/alarms", alarmsHandler)
	http.HandleFunc("/netdata/data", dataHandler)

	fmt.Printf("🚀 Universal Go Streamer listening on %s...\n", ListenPort)
	if err := http.ListenAndServe(ListenPort, nil); err != nil {
		fmt.Printf("❌ Server failed: %v\n", err)
	}
}
