package robots

import (
	"context"
	"strings"
	"testing"

	"github.com/valolink/hestiascripts/internal/hestia"
	"github.com/valolink/hestiascripts/internal/sys"
)

const placeholder = "# hestiacp autogenerated robots.txt\nUser-agent: *\nCrawl-delay: 10\n"

var shop = Facts{Home: "https://soutuveneet.fi", Woo: true, WooPaths: []string{"/ostoskori/", "/kassa/", "/oma-tili/"}, Sitemap: "https://soutuveneet.fi/sitemap_index.xml"}

func TestRenderPlaceholderShop(t *testing.T) {
	got := Render(placeholder, shop)
	for _, want := range []string{"User-agent: *\nCrawl-delay: 10\n\n# hs:robots begin", "Disallow: /*?*product_orderby=", "Disallow: /ostoskori/", "Disallow: /wp-admin/", "Allow: /wp-admin/admin-ajax.php", "\nSitemap: https://soutuveneet.fi/sitemap_index.xml\n# hs:robots end\n"} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in\n%s", want, got)
		}
	}
	if strings.Contains(got, HestiaMarker) {
		t.Error("placeholder comment kept")
	}
	if Render(got, shop) != got {
		t.Errorf("not idempotent:\n%s\n---\n%s", got, Render(got, shop))
	}
	if st := Assess(got, true, shop); st.Kind != "hs" || st.Route != "" {
		t.Errorf("current block: %+v", st)
	}
	moved := shop
	moved.WooPaths = []string{"/cart/"}
	if st := Assess(got, true, moved); st.Route != "file" {
		t.Errorf("stale block: %+v", st)
	}
}

func TestRenderKeepsCustomAndSkipsPresent(t *testing.T) {
	custom := "User-agent: *\nDisallow: /wp-admin/\nAllow: /wp-admin/admin-ajax.php\nDisallow: /private/\n\nSitemap: https://x.fi/wp-sitemap.xml\n"
	got := Render(custom, Facts{Home: "https://x.fi", Sitemap: "https://x.fi/wp-sitemap.xml"})
	if got != custom {
		t.Errorf("nothing to add must leave the file as it is:\n%s", got)
	}
	st := Assess(custom, true, Facts{})
	if st.Kind != "custom" || len(st.Problems) != 0 {
		t.Errorf("fine custom file: %+v", st)
	}
	got = Render(custom, Facts{Woo: true, Sitemap: "https://x.fi/wp-sitemap.xml"})
	if strings.Count(got, "Sitemap:") != 1 || !strings.Contains(got, "Disallow: /private/") || !strings.Contains(got, "Disallow: /*?*orderby=") || strings.Count(got, "Disallow: /wp-admin/") != 1 {
		t.Errorf("custom + woo:\n%s", got)
	}
}

func TestAssessRoutes(t *testing.T) {
	seo := shop
	seo.SEOPlugin = "Rank Math"
	if st := Assess("", false, seo); st.Route != "plugin" {
		t.Errorf("virtual + Rank Math shop: %+v", st)
	}
	if st := Assess(placeholder, true, seo); st.Route != "unshadow" {
		t.Errorf("placeholder + Rank Math: %+v", st)
	}
	if st := Assess(placeholder, true, Facts{}); st.Route != "file" || st.Kind != "hestia" {
		t.Errorf("placeholder: %+v", st)
	}
	if st := Assess("", false, Facts{}); st.Route != "" {
		t.Errorf("virtual, no shop: %+v", st)
	}
}

func TestGather(t *testing.T) {
	d := hestia.Domain{User: "soutuveneet", Name: "soutuveneet.fi", IP: "94.237.113.119", SSL: true}
	f := &sys.Fake{HTTP: map[string]sys.FakeHTTP{
		"local https://soutuveneet.fi/sitemap_index.xml": {Status: 200},
	}}
	answers := map[string]string{
		"plugin list --status=active --field=name --skip-plugins --skip-themes":                                                    "woocommerce\nwordpress-seo\n",
		"option get home --skip-plugins --skip-themes":                                                                             "https://soutuveneet.fi\n",
		"option get woocommerce_cart_page_id --skip-plugins --skip-themes":                                                         "12\n",
		"option get woocommerce_checkout_page_id --skip-plugins --skip-themes":                                                     "13\n",
		"option get woocommerce_myaccount_page_id --skip-plugins --skip-themes":                                                    "0\n",
		"post list --post_type=page --post_status=publish --post__in=12,13 --fields=url --format=csv --skip-plugins --skip-themes": "url\nhttps://soutuveneet.fi/ostoskori/\nhttps://soutuveneet.fi/kassa\n",
	}
	wp := func(_ context.Context, args ...string) (string, error) {
		return answers[strings.Join(args, " ")], nil
	}
	got, err := Gather(context.Background(), f, d, wp)
	if err != nil || !got.Woo || got.SEOPlugin != "" || got.Sitemap != "https://soutuveneet.fi/sitemap_index.xml" ||
		strings.Join(got.WooPaths, ",") != "/ostoskori/,/kassa/" {
		t.Errorf("gather: %+v %v", got, err)
	}
}
