// Package robots keeps a WordPress site's robots.txt useful: a Sitemap line,
// wp-admin closed, and for WooCommerce shops the sort/filter/cart URLs closed
// to crawlers. Everything outside the hs-managed block is left as it is.
//
// Why (soutuveneet.fi, 2026-09-30): PerplexityBot walked every category ×
// ?product_orderby= / product_order= / product_view= / product_count=
// permutation. Every query string bypasses the wp-rocket page cache, so each
// one was a full PHP render — load 15 on two cores. The robots.txt it read was
// Hestia's placeholder ("# hestiacp autogenerated robots.txt", Crawl-delay
// only), which also shadows WordPress's virtual robots.txt, so there was no
// Sitemap line either.
//
// robots.txt is advisory: well-behaved crawlers obey it, the rest need
// enforcement in nginx (a per-domain nginx.ssl.conf_<name> include answering
// 429 by user agent). This package only writes robots.txt.
package robots

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	neturl "net/url"
	"strings"

	"github.com/valolink/hestiascripts/internal/hestia"
	"github.com/valolink/hestiascripts/internal/sys"
)

const (
	Begin = "# hs:robots begin"
	End   = "# hs:robots end"
	// HestiaMarker is the first line of the skeleton robots.txt Hestia puts in
	// every new web domain (install/common/templates/web/skel/public_html).
	HestiaMarker = "# hestiacp autogenerated robots.txt"
)

// WooDisallow: WooCommerce URLs that multiply into endless uncached renders.
var WooDisallow = []string{
	"/*?*orderby=",
	"/*?*product_orderby=",
	"/*?*product_order=",
	"/*?*product_view=",
	"/*?*product_count=",
	"/*?*add-to-cart=",
	"/*?*filter_",
	"/*?*min_price=",
	"/*?*max_price=",
}

// Facts are what the site is, read from the live box.
type Facts struct {
	Home      string   // WordPress home URL, e.g. https://www.example.fi
	Plugins   []string // active plugin slugs
	Woo       bool
	WooPaths  []string // cart, checkout, my-account paths ("/ostoskori/")
	Sitemap   string   // absolute URL that answered 200, "" when none did
	SEOPlugin string   // a plugin that serves robots.txt rules itself (virtual)
}

// seoVirtual: plugins whose robots.txt settings only reach the virtual
// robots.txt — a physical file silently overrides them. (Yoast's editor
// writes the physical file itself, so it is not in this list.)
var seoVirtual = map[string]string{
	"seo-by-rank-math":     "Rank Math",
	"seo-by-rank-math-pro": "Rank Math",
	"wp-seopress":          "SEOPress",
	"wp-seopress-pro":      "SEOPress",
	"all-in-one-seo-pack":  "All in One SEO",
}

// sitemapCandidates by plugin, then WordPress core's own.
func sitemapCandidates(plugins []string) []string {
	var out []string
	for _, p := range plugins {
		switch p {
		case "wordpress-seo", "wordpress-seo-premium", "seo-by-rank-math", "seo-by-rank-math-pro":
			out = append(out, "/sitemap_index.xml")
		case "wp-seopress", "wp-seopress-pro":
			out = append(out, "/sitemaps.xml")
		case "all-in-one-seo-pack", "autodescription":
			out = append(out, "/sitemap.xml")
		}
	}
	return append(out, "/wp-sitemap.xml")
}

// WPFunc runs WP-CLI as the site's user (site.WP, bound to a domain).
type WPFunc func(ctx context.Context, args ...string) (string, error)

// Gather reads the facts. Read-only: plugin and option reads with plugins
// and themes skipped, and local HTTP probes for the sitemap.
func Gather(ctx context.Context, s sys.Sys, d hestia.Domain, wp WPFunc) (Facts, error) {
	var f Facts
	out, err := wp(ctx, "plugin", "list", "--status=active", "--field=name", "--skip-plugins", "--skip-themes")
	if err != nil {
		return f, err
	}
	for _, l := range strings.Split(out, "\n") {
		if l = strings.TrimSpace(l); l != "" {
			f.Plugins = append(f.Plugins, l)
			if l == "woocommerce" {
				f.Woo = true
			}
			if name, ok := seoVirtual[l]; ok && f.SEOPlugin == "" {
				f.SEOPlugin = name
			}
		}
	}
	if h, err := wp(ctx, "option", "get", "home", "--skip-plugins", "--skip-themes"); err == nil {
		f.Home = strings.TrimRight(strings.TrimSpace(h), "/")
	}
	if f.Home == "" {
		scheme := "http"
		if d.SSL {
			scheme = "https"
		}
		f.Home = scheme + "://" + d.Name
	}
	if f.Woo {
		f.WooPaths = wooPaths(ctx, wp)
	}
	f.Sitemap = findSitemap(ctx, s, d, f)
	return f, nil
}

func wooPaths(ctx context.Context, wp WPFunc) []string {
	var ids []string
	for _, opt := range []string{"woocommerce_cart_page_id", "woocommerce_checkout_page_id", "woocommerce_myaccount_page_id"} {
		v, err := wp(ctx, "option", "get", opt, "--skip-plugins", "--skip-themes")
		if v = strings.TrimSpace(v); err == nil && v != "" && v != "0" && strings.Trim(v, "0123456789") == "" {
			ids = append(ids, v)
		}
	}
	if len(ids) == 0 {
		return nil
	}
	out, err := wp(ctx, "post", "list", "--post_type=page", "--post_status=publish", "--post__in="+strings.Join(ids, ","),
		"--fields=url", "--format=csv", "--skip-plugins", "--skip-themes")
	if err != nil {
		return nil
	}
	var paths []string
	for _, l := range strings.Split(out, "\n") {
		l = strings.Trim(strings.TrimSpace(l), `"`)
		if !strings.HasPrefix(l, "http") {
			continue // the csv header ("url")
		}
		u, err := neturl.Parse(l)
		if err != nil || u.Path == "" || u.Path == "/" {
			continue // a shop page on the front page must never be disallowed
		}
		p := u.Path
		if !strings.HasSuffix(p, "/") {
			p += "/"
		}
		paths = append(paths, p)
	}
	return paths
}

func findSitemap(ctx context.Context, s sys.Sys, d hestia.Domain, f Facts) string {
	base, err := neturl.Parse(f.Home)
	if err != nil || base.Host == "" {
		return ""
	}
	seen := map[string]bool{}
	for _, c := range sitemapCandidates(f.Plugins) {
		if seen[c] {
			continue
		}
		seen[c] = true
		u := strings.TrimRight(f.Home, "/") + c
		code, loc, err := s.HTTPLocal(ctx, u, d.IP)
		if err == nil && code == 200 {
			return u
		}
		// wp-sitemap.xml and some plugins redirect to the index they serve
		if err == nil && code >= 300 && code < 400 && loc != "" {
			if next, err := base.Parse(loc); err == nil && next.Host == base.Host {
				if c2, _, err := s.HTTPLocal(ctx, next.String(), d.IP); err == nil && c2 == 200 {
					return next.String()
				}
			}
		}
	}
	return ""
}

// Outside returns the file without the hs block and without Hestia's
// placeholder comment, trailing blank lines trimmed.
func Outside(existing string) string {
	var out []string
	in := false
	for _, l := range strings.Split(strings.ReplaceAll(existing, "\r\n", "\n"), "\n") {
		t := strings.TrimSpace(l)
		switch {
		case strings.HasPrefix(t, Begin):
			in = true
			continue
		case strings.HasPrefix(t, End):
			in = false
			continue
		case in:
			continue
		case t == HestiaMarker:
			continue
		}
		out = append(out, l)
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n \t")
}

func norm(l string) string {
	k, v, ok := strings.Cut(strings.TrimSpace(l), ":")
	if !ok {
		return ""
	}
	return strings.ToLower(strings.TrimSpace(k)) + ":" + strings.TrimSpace(v)
}

func has(text, key, value string) bool {
	want := strings.ToLower(key) + ":" + value
	for _, l := range strings.Split(text, "\n") {
		if norm(l) == want {
			return true
		}
	}
	return false
}

func hasKey(text, key string) bool {
	for _, l := range strings.Split(text, "\n") {
		if strings.HasPrefix(norm(l), strings.ToLower(key)+":") {
			return true
		}
	}
	return false
}

// Block is the hs-managed block for these facts, given what the rest of the
// file already says. Empty when there is nothing to add.
func Block(outside string, f Facts) []string {
	var rules []string
	add := func(k, v string) {
		if !has(outside, k, v) {
			rules = append(rules, k+": "+v)
		}
	}
	add("Disallow", "/wp-admin/")
	add("Allow", "/wp-admin/admin-ajax.php") // front-end AJAX (cart fragments, filters) lives there
	if f.Woo {
		for _, p := range WooDisallow {
			add("Disallow", p)
		}
		for _, p := range f.WooPaths {
			add("Disallow", p)
		}
	}
	var sitemap []string
	if f.Sitemap != "" && !hasKey(outside, "Sitemap") {
		sitemap = []string{"", "Sitemap: " + f.Sitemap}
	}
	if len(rules) == 0 && len(sitemap) == 0 {
		return nil
	}
	block := []string{Begin, "# written by hs (hs fix robots); lines between the markers are replaced on every run"}
	if len(rules) > 0 {
		block = append(block, "User-agent: *")
		block = append(block, rules...)
	}
	block = append(block, sitemap...)
	return append(block, End)
}

// Rules are the block's directives without the markers — what to paste into
// an SEO plugin's robots.txt editor instead.
func Rules(f Facts) []string {
	b := Block("", f)
	if len(b) < 3 {
		return nil
	}
	var out []string
	for _, l := range b[2 : len(b)-1] {
		if l != "" {
			out = append(out, l)
		}
	}
	return out
}

// Render is the whole file hs would write.
func Render(existing string, f Facts) string {
	out := Outside(existing)
	block := Block(out, f)
	if len(block) == 0 {
		if out == "" {
			return ""
		}
		return out + "\n"
	}
	if out != "" {
		out += "\n\n"
	}
	return out + strings.Join(block, "\n") + "\n"
}

// Sum identifies a rendered file: the plan shows it, the write refuses any
// other content (what you approve is what runs).
func Sum(content string) string {
	h := sha256.Sum256([]byte(content))
	return hex.EncodeToString(h[:8])
}

// State is the check's reading of a site's robots.txt.
type State struct {
	Kind     string   // "virtual", "hestia", "hs", "custom"
	Problems []string // what is missing, plain language
	Route    string   // "file" (hs fix robots), "plugin" (the SEO plugin's editor), "unshadow", "" (fine)
}

// Assess reads the physical file (exists=false: WordPress serves a virtual one).
func Assess(existing string, exists bool, f Facts) State {
	var st State
	switch {
	case !exists:
		st.Kind = "virtual"
		if f.Woo {
			st.Problems = append(st.Problems, "no WooCommerce rules: crawlers may render every sort/filter/cart URL")
			st.Route = "file"
			if f.SEOPlugin != "" {
				st.Route = "plugin"
			}
		}
		return st
	case strings.Contains(existing, Begin):
		st.Kind = "hs"
		if Render(existing, f) != existing {
			st.Problems = append(st.Problems, "the hs block is out of date (sitemap or WooCommerce pages changed)")
			st.Route = "file"
		}
		return st
	case strings.Contains(existing, HestiaMarker):
		st.Kind = "hestia"
		st.Problems = append(st.Problems, "Hestia's placeholder shadows WordPress's robots.txt: no Sitemap line, no wp-admin rule")
		if f.Woo {
			st.Problems = append(st.Problems, "no WooCommerce rules: crawlers may render every sort/filter/cart URL")
		}
		st.Route = "file"
		if f.SEOPlugin != "" {
			st.Problems = append(st.Problems, "it also hides "+f.SEOPlugin+"'s robots.txt rules")
			st.Route = "unshadow"
		}
		return st
	}
	st.Kind = "custom"
	if !hasKey(existing, "Sitemap") {
		st.Problems = append(st.Problems, "no Sitemap line")
	}
	if f.Woo && !strings.Contains(strings.ToLower(existing), "orderby") {
		st.Problems = append(st.Problems, "no WooCommerce rules: crawlers may render every sort/filter/cart URL")
	}
	if len(st.Problems) > 0 {
		st.Route = "file"
		if f.SEOPlugin != "" {
			st.Problems = append(st.Problems, "this file overrides "+f.SEOPlugin+"'s robots.txt rules")
		}
	}
	return st
}

// Path of a site's physical robots.txt.
func Path(d hestia.Domain) string { return d.DocRoot() + "/robots.txt" }

// Describe the facts in one evidence line.
func (f Facts) String() string {
	var parts []string
	if f.Woo {
		parts = append(parts, fmt.Sprintf("WooCommerce (pages %s)", strings.Join(f.WooPaths, " ")))
	}
	if f.SEOPlugin != "" {
		parts = append(parts, f.SEOPlugin+" manages robots rules")
	}
	if f.Sitemap != "" {
		parts = append(parts, "sitemap "+f.Sitemap)
	} else {
		parts = append(parts, "no sitemap answered")
	}
	return strings.Join(parts, "; ")
}
